Repository TheLodge-CulinaryChaos/CulinaryChaos, pull requests merged in 2024-10, with the labels that each got.

#28 #10 - basic order and ingredient class definitions
  Assets/Scenes/Easy.unity
  Assets/Scripts/Objects/Corn.cs
  Assets/Scripts/Objects/Corn.cs.meta
  Assets/Scripts/Objects/Ingredient.cs
  Assets/Scripts/Objects/Ingredient.cs.meta
  Assets/Scripts/Objects/Lettuce.cs
  Assets/Scripts/Objects/Lettuce.cs.meta
  Assets/Scripts/Objects/Order.cs
  Assets/Scripts/Objects/Order.cs.meta
  Assets/Scripts/Objects/Tomato.cs
  Assets/Scripts/Objects/Tomato.cs.meta
Labels: assets

#30 Angela/animation audio
  Assets/Animations/Player/Imported/Walking Normal animation.anim
  Assets/Animations/Player/Imported/Walking Normal animation.anim.meta
  Assets/Animations/Player/Official/Jump.anim
  Assets/Animators/Player/Locomotion.controller
  Assets/Art/Imported Models.meta
  Assets/Art/Imported Models/Kitchen 1.meta
  Assets/Art/Imported Models/Kitchen 1/FreeKitchen.meta
  Assets/Art/Imported Models/Kitchen 1/FreeKitchen/SRP UpgradePackage.meta
  Assets/Art/Imported Models/Kitchen 1/FreeKitchen/SRP UpgradePackage/Built-in_Material.unitypackage.meta
  Assets/Art/Imported Models/Kitchen 1/FreeKitchen/SRP UpgradePackage/URP_Material.unitypackage.meta
  Assets/PlayerFootStepSound.cs
  Assets/PlayerFootStepSound.cs.meta
  Assets/Scenes/Easy.unity
  Assets/Sound.meta
  Assets/Sound/player_footstep.wav
  Assets/Sound/player_footstep.wav.meta
Labels: priority: medium, assets

#45 animate door open/close
  Assets/Animators/Door.meta
  Assets/Animators/Door/Door.controller
  Assets/Animators/Door/Door.controller.meta
  Assets/Animators/Door/DoorClose.anim
  Assets/Animators/Door/DoorClose.anim.meta
  Assets/Animators/Door/DoorOpen.anim
  Assets/Animators/Door/DoorOpen.anim.meta
  Assets/Scenes/Easy.unity
  Assets/Scenes/Easy.unity.orig
  Assets/Scripts/NPC/npcAI.cs
  ProjectSettings/TagManager.asset
Labels: feature, priority: high

#46 Angela/pickup and landing audio
  Assets/Animations/Player/Official/Jump.anim
  Assets/Animations/Player/Official/Pick Fruit.anim
  Assets/Animators/Player/Locomotion.controller
  Assets/Art/Characters/MainPlayer/RPG Tiny Hero Duo/Animation/SwordAndShield/InPlace/JumpEnd_Normal.anim
  Assets/Art/Characters/MainPlayer/RPG Tiny Hero Duo/Animation/SwordAndShield/InPlace/JumpEnd_Normal.anim.meta
  Assets/Art/Imported Models/Kitchen 1/FreeKitchen/SRP UpgradePackage/Built-in_Material.unitypackage.meta
  Assets/Art/Imported Models/Kitchen 1/FreeKitchen/SRP UpgradePackage/URP_Material.unitypackage.meta
  Assets/Scenes/Easy.unity
  Assets/Scripts/Player/PickUpSound.cs
  Assets/Scripts/Player/PickUpSound.cs.meta
  Assets/Scripts/Player/PlayerLandingSound.cs
  Assets/Scripts/Player/PlayerLandingSound.cs.meta
  Assets/Sound/land.wav
  Assets/Sound/land.wav.meta
  Assets/Sound/pickup.wav
  Assets/Sound/pickup.wav.meta
  UIElementsSchema/GlobalNamespace.xsd
  UIElementsSchema/UIElements.xsd
  UIElementsSchema/Unity.Profiling.Editor.xsd
  UIElementsSchema/Unity.UI.Builder.xsd
  UIElementsSchema/UnityEditor.Experimental.GraphView.xsd
  UIElementsSchema/UnityEditor.Overlays.xsd
  UIElementsSchema/UnityEditor.PackageManager.UI.Internal.xsd
  UIElementsSchema/UnityEditor.Rendering.LookDev.xsd
  UIElementsSchema/UnityEditor.Search.xsd
  UIElementsSchema/UnityEditor.ShaderGraph.Drawing.xsd
  UIElementsSchema/UnityEditor.ShortcutManagement.xsd
  UIElementsSchema/UnityEditor.UIElements.Debugger.xsd
  UIElementsSchema/UnityEditor.UIElements.xsd
  UIElementsSchema/UnityEngine.UIElements.xsd
Labels: enhancement, priority: low, assets

#58 Misc/fix conflict
  Assets/Scenes/Easy.unity
Labels: bug: minor

#50 Katelynn / [14] order generation system + [41] simple order UI
  Assets/Scenes/Easy.unity
  Assets/Scenes/Easy.unity.orig
  Assets/Scripts/NPC/npcAI.cs
  Assets/Scripts/Objects/Order.cs
  Assets/Scripts/Objects/OrderSystem.cs
  Assets/Scripts/Objects/OrderSystem.cs.meta
  Assets/Scripts/Objects/OrderUI.cs
  Assets/Scripts/Objects/OrderUI.cs.meta
  Assets/Scripts/Objects/Recipe.cs
  Assets/Scripts/Objects/Recipe.cs.meta
  Assets/Scripts/Utility/Orders.cs
  Assets/UI.meta
  Assets/UI/Prefab.meta
  Assets/UI/Prefab/Orders Panel.prefab
  Assets/UI/Prefab/Orders Panel.prefab.meta
Labels: feature, priority: high

#64 Handing the Round Ending
  Assets/PNGs/Gameplay Next Level.png
  Assets/PNGs/Gameplay Next Level.png.meta
  Assets/RoundOver.cs
  Assets/RoundOver.cs.meta
  Assets/Scenes/Easy.unity
  Assets/Scripts/Utility/Coins.cs
  Assets/Scripts/Utility/Timer.cs
  Assets/Summary.cs
  Assets/Summary.cs.meta
Labels: feature, priority: high

#70 added audio system handler
  Assets/Animations/Player/Official/Base Locomotion/SprintFWD.anim
  Assets/Animations/Player/Official/Hold Plate/MoveFWD_Holding.anim
  Assets/Animations/Player/Official/Pick Fruit.anim
  Assets/AudioManager.cs
  Assets/AudioManager.cs.meta
  Assets/Scenes/Easy.unity
Labels: enhancement, priority: medium, assets

#72 Quick fix
  Assets/AudioManager.cs
  Assets/Scenes/Easy.unity
Labels: bug: critical

#73 Thuan/readme
  Assets/Scenes/Easy.unity
  Assets/TextMesh Pro/Resources/Fonts & Materials/Mesh - LiberationSans SDF.mat
  Assets/TextMesh Pro/Resources/Fonts & Materials/Mesh - LiberationSans SDF.mat.meta
  Assets/UI/Prefab/Orders Panel.prefab
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/ProjectSettings.asset
  README.md
  TheLodge_CulinaryChaos_readme.txt
Labels: documentation
